Implement Date#deconstruct_keys and DateTime#deconstruct_keys
ruby/date pull request #80
Opened 2022-12-06 17:59 UTC by zverok

Same as https://github.com/ruby/ruby/pull/6594, but for `Date` & `DateTime`.

2022-12-06 20:11 UTC, zverok commented
Hmm, interesting, it seems to only be compilable under 3.2 :thinking: 
Should I surround new code with a version-specific macro?

2022-12-08 16:29 UTC, jeremyevans commented
Sorry that I haven't had a chance to review this yet, I'm currently at RubyConfTH and haven't had a lot of free time.  I should be able to review next week.

From a brief review of the build error, you can probably switch from `rb_hash_new_capa` to just `rb_hash_new`.  Unless you can see a significant performance improvement from using `rb_hash_new_capa` on 3.2, I would avoid the optimization and keep the code the same for all ruby versions.

2022-12-10 11:50 UTC, zverok commented
@jeremyevans Yeah, makes sense. All green now.

2022-12-11 17:06 UTC, jeremyevans requested changes
Looks good, thanks for working on this.  I have some minor requests for changes, then this can be merged.

2022-12-11 17:06 UTC, jeremyevans commented on ext/date/date_core.c
> +        h = rb_hash_new();
You could do `VALUE h = rb_hash_new();` and eliminate the two lines for setting `h`, since they are now the same.

2022-12-11 17:06 UTC, jeremyevans commented on test/date/test_date.rb
> +    assert_equal({year: 1999}, d.deconstruct_keys([:year, :century]))
Can you add an assertion that tests for all valid keys, both for Date and DateTime, so all branches get covered?

2022-12-13 03:10 UTC, jeremyevans approved these changes

2022-12-13 19:52 UTC, merged